sprinng:
  application:
    name: cambio-service

server:
  port: 8000

spring:
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
