spring:
  application:
    name: book-service
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: mysql
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: mysql

resilience4j:
  retry:
    instances:
      book-service:
        max-attempts: 8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
